try {
    func();
} catch (e) {
    log(e);
} finally {
    log();
}